### ISSUE TITLE
💡 RFC: Add support for numerals (III IV)

### ISSUE THREAD

**Issue by isaiahdahl** [PraiseCharts/ChordChartJS#20]
### Background & Motivation

It's a pretty straightforward feature. Allow for Numerals to be a 'key' you can switch to.

The catch with numerals is that minor chords are lowercase and major chords are uppercase.

"ii == 2m == Gm" and "II == 2 == G"

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by martijnversluis** [comment]
@isaiahdahl As far as you know, is there a notation for numerals to transpose up or down by one semitone, just like numerics (eg. `#4` and `b5`)?

**Comment by isaiahdahl** [comment]
Yes same as numbers. #IV bV

**Comment by martijnversluis** [comment]
And what is allowed for bass notes? Only uppercase or both?

**Comment by isaiahdahl** [comment]
Both

**Comment by isaiahdahl** [comment]
@martijnversluis  I'm actually having a hard time finding a real live example of a base note that's minor. Practically the team thinks it's possible. But I'm trying to find a real example in our catalog.

**Comment by isaiahdahl** [comment]
@martijnversluis So I think it's safe to just not worry about the bass note being minor. I'm retracting my "Both" comment.
